language: csharp
mono: none
dotnet: 2.2.401

env:
  global:
    - secure: "cTZ/NtbAT83dysNpzuRWbh0Cia4YY4WnWqx0dFq98rNeXE02+UjCL7q0dWmhkSxvP8YYvXMXj+13J/NAH0sPyrXR+BIOsDEpR8aoB6gaGh5H6FkONq41JZcfFd5/s4OsuZ/QlMSK21oAPOZU9K+tHjrb5xUf9osey9OBx+HNlcY=" #ConsumerKey
    - secure: "Fmz1IrfGgcKKIAvBccKn5Hi/kKpE+Hs/hJAOIhTBniInMcoE0dcUCNYCV16uYjDvUsVNDDi0Tz/bk/UJh8kZNPJkkCQfys60l7Bl/mZ2r6umaBuiS0Xp0ZKSabsCnCLZWUSfIJdCEMgqBWOFNicfuXHRd/h0n31Pe2qFOwCzwA8=" #ConsumerSecret
    - secure: "M1875n8CTGSc50Vufd+V4FgdvdSHPqvnHLJmk3MBSCSPRBQ15FvxtSCPY24cDgCzNyOA3dSOkISGj1bwNj607QB4ao1sFK8ytIhwFgSC3udlSUu/b+3FyI1RSD5j5ZT9qB74nna+0hsijU6txMAf8vVWI9dorZCYCDAlaSEbU1Y=" #Username
    - secure: "gKbbduuB3GslGVGr0IsFnearI2EDm/PD/EYum2zRDvZsRHy2b4uMl2tpSCjF382PKXWk46ZJ2c2zIvqcxgfHc0NDqloMAH6wwE4VnEDBk5j22X+ea50tdjB0r+RcjG5SbdjqYSSUxM3Ygngl87LfWAZGPWfL5Nm14L/4rhT3cj8=" #Password
    - secure: "Ez7qB2PZ/gBXCdOirR0jqcOYDRK9DtPiBFg9p9LTo4VTNZ6UqBrpPLsKGyQSry/zzvI532Y8vtOPL8PNpBaGOexyJ6M0fWQUjjT0/+p53w3syhYRiqJZOiY0PWoq2beRYIFScUNzbaRdZL4cDNsLHaNV+h8KGTYZ+gVXhYerU94=" #OrganizationId

script:
  - dotnet build src/ForceToolkitForNET.sln -f netstandard2.0
  - dotnet test tests/ForceToolkitForNET.Tests.sln --list-tests
  - dotnet test tests/ForceToolkitForNET.Tests.sln /p:CollectCoverage=true
